# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Material Blog
name: John Doe
email: john.doe@example.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
host: "example.com"
url: "https://example.com" # the base hostname & protocol for your site
github_username:  "example"
disqus_username:

# Enable this and add your cookie ID to analytics.js
analytics: "false"

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/
incremental: true

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "<!--more-->"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: "_sass"
  style: compressed

images: '/assets/images'

plugins:
  - jekyll-seo-tag
